spring.application.name=eCom_Project_2026

#spring.h2.console.enabled=true

#spring.datasource.url= jdbc:h2:mem:wolfsRealm

#spring.datasource.url= jdbc:mysql://localhost:3306/eCom_Project_2026
#spring.datasource.username=root
#spring.datasource.password=115821033371845@Prasad

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eCom_Project_2026}
spring.datasource.username=postgres
spring.datasource.password=115821033371845@Prasad

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

project.image=images/

spring.app.jwtSecret= ZLxvcdNS8Fg7kE441GxGptY+RwPU52engXz7/V/FZc8=
spring.app.jwtExpirationMs= 3000000
spring.app.jwtCookieName= springBootEcomProject2026

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.wolfsRealm.ecom_project_2026=DEBUG

#for actuator
management.endpoints.web.exposure.include=*
# here instead od doing *, we can do something like beans,loggers,health,metrics,info
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name= eCommerce Spring Boot Application
info.app.version=6.9
info.owner.name=Prasad (Dada) Kulkarni
info.owner.contact=8263066910
info.owner.emailId=prasadkulkarni2409@gmail.com


management.endpoint.shutdown.access=unrestricted

