spring.application.name=eCom_Project_2026

spring.h2.console.enabled=true

spring.datasource.url= jdbc:h2:mem:wolfsRealm

spring.datasource.username=YoungWolf

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create-drop

project.image=images/

spring.app.jwtSecret=mySecretKey115821033371845fgjnsgjksgnkmdfvmgvlmsfbvkmn
spring.app.jwtExpirationMs= 3000000
spring.app.jwtCookieName= springBootEcomProject2026

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.wolfsRealm.ecom_project_2026=DEBUG
