spring.application.name=eCom_Project_2026

spring.h2.console.enabled=true

spring.datasource.url= jdbc:h2:mem:wolfsRealm

spring.datasource.username=YoungWolf

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create-drop